version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_LIVE2D_MODEL_PATH=${VITE_LIVE2D_MODEL_PATH:-/live2d_models/furina/furina.model3.json}
      - VITE_LIVE2D_MODEL_WIDTH=${VITE_LIVE2D_MODEL_WIDTH:-280}
      - VITE_LIVE2D_MODEL_HEIGHT=${VITE_LIVE2D_MODEL_HEIGHT:-400}
      - VITE_LIVE2D_MODEL_MOBILE_WIDTH=${VITE_LIVE2D_MODEL_MOBILE_WIDTH:-200}
      - VITE_LIVE2D_MODEL_MOBILE_HEIGHT=${VITE_LIVE2D_MODEL_MOBILE_HEIGHT:-300}
    depends_on:
      - backend
    restart: unless-stopped
    # 多架构性能优化
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "5000:5000"
    volumes:
      - ./backend/instance:/app/instance
      - ./backend/uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    restart: unless-stopped
    # 多架构性能优化
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  default:
    driver: bridge
