services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    environment:
      - VITE_LIVE2D_MODEL_PATH=${VITE_LIVE2D_MODEL_PATH} 
      - VITE_LIVE2D_MODEL_WIDTH=${VITE_LIVE2D_MODEL_WIDTH}
      - VITE_LIVE2D_MODEL_HEIGHT=${VITE_LIVE2D_MODEL_HEIGHT}
      - VITE_LIVE2D_MODEL_MOBILE_WIDTH=${VITE_LIVE2D_MODEL_MOBILE_WIDTH}
      - VITE_LIVE2D_MODEL_MOBILE_HEIGHT=${VITE_LIVE2D_MODEL_MOBILE_HEIGHT}
      - DOCKER_ENV=true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/instance:/app/instance 
    environment:
      - PYTHONUNBUFFERED=1 
    command: >
      gunicorn -w 4 -b 0.0.0.0:5000 --log-file - --error-logfile - "run:app"