"""Initial database setup

Revision ID: 513ded74ae49
Revises: 
Create Date: 2025-07-31 07:19:44.457149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513ded74ae49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=False),
    sa.Column('startup_time', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_metrics')
    op.drop_table('post')
    # ### end Alembic commands ###
